version: '2'
services:
  # container for API
    api:
        image: toancong/phpup:2.2.2
        ports:
          - 9085:80
        depends_on:
          - db
        volumes:
          - .:/var/www/app
        environment:
          - PHP_MEM_LIMIT=1024M
    db:
        image: mysql:5.7
        ports:
          - 3301:3306
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: user123
    dbtest:
      image: mysql:5.7
      ports:
        - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dbtest
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: user123
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 9002:80
        depends_on:
          - db
          - dbtest
        environment:
            PMA_HOSTS: db, dbtest
            PMA_USER: dbuser
            PMA_PASSWORD: user123
